services:
  postgres:
    image: postgres
    env_file:
      - ./env/.env
    volumes:
      - ./db/data:/var/lib/postgresql/data
    ports:
      - 5433:5432

  mongo:
    image: mongo
    restart: always
    env_file:
      - ./env/.env
    ports:
      - 27017:27017